name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        env:
          CI: false
      
      - name: Debug - List all files
        run: |
          echo "=== Root directory ==="
          ls -la
          echo "=== Build output directory ==="
          ls -la dist/ || echo "dist directory not found"
          echo "=== dist/index.html content (first 10 lines) ==="
          head -10 dist/index.html || echo "dist/index.html not found"
          echo "=== firebase.json content ==="
          cat firebase.json || echo "firebase.json not found"
        
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: any-qr-react
